font_family Maple Mono NF
include kitty.d/**/*.conf
active_tab_font_style bold-italic
enable_audio_bell no
inactive_tab_font_style normal
macos_option_as_alt yes
tab_bar_style powerline
visual_bell_duration 0.1

active_tab_background #3c3836
active_tab_foreground #d4be98
inactive_tab_background #32302f
inactive_tab_foreground #d4be98

map alt+h previous_tab
map alt+l next_tab
map kitty_mod+r kitten resize_window




# BEGIN_KITTY_THEME
# Gruvbox Material Dark Medium
include current-theme.conf
# END_KITTY_THEME
